name: cabgo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  easy_debounce: ^2.0.2+1
  flutter_credit_card: ^3.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  location: ^4.4.0
  google_maps_flutter: ^2.1.6
  json_path: ^0.4.0
  page_transition: ^2.0.5
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.2.2
  geolocator: ^9.0.1
  google_maps_webservice: ^0.0.19
  geocoding: ^2.0.4
  provider: ^6.0.3
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.0
  flutter_google_places: ^0.3.0
  geocode: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^6.0.0
  firebase_core: ^1.17.1
  firebase_messaging: ^12.0.2
  flutter_ringtone_player: ^3.2.0
  flutter_local_notifications: ^9.7.1
  google_place: ^0.4.7
  progress_dialog: ^1.2.4
  colorful_safe_area: ^0.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  loading_indicator: ^3.0.3
  flutter_progress_hud: ^2.0.2
  dash_chat_2: ^0.0.11
  flutter_firebase_chat_core: ^1.5.4
  device_info_plus: ^4.0.0
  smooth_star_rating: ^1.1.1
  internet_connection_checker: ^0.0.1+4

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/cg_logo.png"
  adaptive_icon_foreground: "assets/images/cg_logo.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - .env


